version: '3.8'

services:
  web:
    build: ./front
    command: python3 -Wd manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    volumes:
      - ./front:/code
      - ./documents:/code/documents
    ports:
      - 8000:8000
    env_file:
      - front/.env

  api:
    build: ./api
    command: python3 -Wd manage.py runserver 0.0.0.0:8003
    volumes:
      - ./api:/code
      - ./documents:/code/documents
    expose:
      - 8003
    env_file:
      - api/.env

  db:
      image: postgres:13
      volumes:
        - ./postgres_data:/var/lib/postgresql/data/
      environment:
        - POSTGRES_USER=atus
        - POSTGRES_PASSWORD=88658710
        - POSTGRES_DB=atus_dev
      hostname: db

#  pgadmin:
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: "atus@atus.com"
#      PGADMIN_DEFAULT_PASSWORD: "88658710"
#    ports:
#      - "8800:80"
#    depends_on:
#      - db
#    networks:
#      - atus
